### PR TITLE
support empty frames in elemntwise operations

### LINKED ISSUE #14: BUG: elementwise operations with empty Frame raise IndexError
```
In[1]: import sparsity as sp
In[2]: import numpy as np
In[3]: a = sp.SparseFrame([], columns=['A', 'B'])
In[4]: a = sp.SparseFrame(np.array([]), columns=['A', 'B'])
In[5]: a
Out[5]: 
Empty DataFrame
[0x2 SparseFrame of type '<class 'float64'>' 
 with 0 stored elements in Compressed Sparse Row format]
In[6]: a.empty
Out[6]: True
In[7]: b = sp.SparseFrame(np.array([[1,0 ], [0, 1]]), columns=['A', 'B'])
In[8]: a.add(b)
Traceback (most recent call last):
  File "/Users/kayibal/virtualenvs/is24/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-a1cb1b03d031>", line 1, in <module>
    a.add(b)
  File "/Users/kayibal/Code/traildb_to_sparse/traildb_to_sparse/traildb_to_sparse/sparsity/sparse_frame.py", line 414, in add
    how=how)
  File "/Users/kayibal/Code/traildb_to_sparse/traildb_to_sparse/traildb_to_sparse/sparsity/sparse_frame.py", line 606, in _aligned_csr_elop
    a_new = sparse.csr_matrix(a[lidx])
  File "/Users/kayibal/virtualenvs/is24/lib/python3.5/site-packages/scipy/sparse/csr.py", line 316, in __getitem__
    P = extractor(row, self.shape[0])     # [[1,2],j] or [[1,2],1:2]
  File "/Users/kayibal/virtualenvs/is24/lib/python3.5/site-packages/scipy/sparse/csr.py", line 270, in extractor
    (min_indx,max_indx) = check_bounds(indices,N)
  File "/Users/kayibal/virtualenvs/is24/lib/python3.5/site-packages/scipy/sparse/csr.py", line 260, in check_bounds
    raise IndexError('index (%d) out of range' % (N + min_indx))
IndexError: index (-1) out of range
```

### PR DESCRIPTION
**Pull request by kayibal**
fixes #14

### CODE REVIEW

**Comment by kayibal** [comment]
good point ... In pandas it depends on fill_value parameter see here:
```
In [7]: b.add(a)
Out[7]:
     a    b
0  NaN  NaN
1  NaN  NaN

In [8]: b.add(a, fill_value=0)
Out[8]:
   a  b
0  0  1
1  1  0
```
But I think this value is kind of implicit when working with sparse matrizes... right?

**Comment by michcio1234** [comment]
Hm, empty frame is different than all-zeros frame. In my opinion, we should unify APIs whenever possible to avoid confusion.

**Comment by kayibal** [comment]
Hm so pandas has the default fill_value set to NaN which makes sense but any other fill_value than 0 wouldn't make sense for sparse data as we would end up with a dense matrix. So Maybe here it makes sense to diverge from the expected pandas behaviour as it would make no sense on Sparse Data. We should accept fill-value parmeter though an raise error if it is set to anything else then 0..

**Comment by michcio1234** [comment]
I agree that we shouldn't accept any other fill value than 0. But I'm still not convinced that it should be a default value. I'd make NaN a default and... raise an error by default. Maybe it seems stupid, but in my opinion it's most confusion-proof. I'm sure I've seen something like this in dask with `axis` parameter. 
But I won't insist. But if I ever make a bug because of it I'll change it without asking. :P

**Comment by kayibal** [comment]
OK raising error by default had the same Idea but it's really ugly. Whereas dask is actually building dask.DataFrame which should be the same as pandas.DataFrame just distributed and sparsit.SparseFrame is not really identical to pandas.DataFrame but rather has similar interface as far as it makes sense :)
I'd be ok if you change it in case a bug makes you angry :P

**Pull request merged**
