### PR TITLE
Getitem and loc failed when all labels were requested.

### PR DESCRIPTION
**Pull request by michcio1234**

### CODE REVIEW

**Comment by michcio1234** [comment]
Master also fails on CircleCI. I guess it's because of new dask.

**Comment by kayibal** [comment]
we will probably have to update dask sparse frame according to this:
http://dask.pydata.org/en/latest/custom-collections.html

**Comment by michcio1234** [comment]
@kayibal I rebased it onto new master, tests pass now. Can we merge it?

**Comment by kayibal** [comment]
Hm does this work `sf.loc[:,:]`? Is this relevant here? If not I'm ok to merge it!

**Comment by michcio1234** [comment]
Added tests for that, it works. Gonna merge it.

**Pull request merged**
